language: node_js
node_js: --lts
before_install:
  - npm install -g hexo-cli
install:
  - cd docs
  - npm install
  - npm install hexo-deployer-git --save
  - cd ..
before_script:
  - git config user.name "XiaoYuxuan"
  - git config user.email "qpalwo@qq.com"
  - sed -i'' "s~https://github.com/qpalwo/blog.git~https://${GITHUB_ACCESS_TOKEN}@github.com/qpalwo/blog.git~" docs/_config.yml
script:
  - hexo --cwd docs clean
  - hexo --cwd docs g
  - echo 'blog.stdxyx.com' > docs/public/CNAME
  - hexo --cwd docs d
